### ISSUE TITLE
Bug: levels argument is required for float input types

### ISSUE THREAD

**Issue by wlievens** [titusjan/argos#14]
Version info:

![image](https://user-images.githubusercontent.com/1073326/68373795-e125aa00-0143-11ea-8761-d1615c4cefcc.png)

I get the following dialog on a particular HDF5 test file generated with h5py (attached).

![image](https://user-images.githubusercontent.com/1073326/68373517-6066ae00-0143-11ea-9b8f-8678225da47f.png)

The error in question happens when activating 2D Image Plot view on node `mode_low_gain/example_sequence/rts/<RESULTS>/map`.

![image](https://user-images.githubusercontent.com/1073326/68373722-bc313700-0143-11ea-834e-1d736d1af995.png)

The zipped HDF5 file is here:

[test.zip](https://github.com/titusjan/argos/files/3818620/test.zip)

**Comment by titusjan** [comment]
Thanks for the bug report. I've encounter errors like this before when the data had a small range (e.g. all zeros like your data set). That's one of the reasons I started to write a new color bar in PyQtGraph ([PgColorBar](https://github.com/titusjan/pgcolorbar)). The development branch already uses this and therefore does not give the error above.

I haven't made a release so far. Is it possible for you to clone the development branch for the time being? You will need to install the following dependencies as well: `cmlib` and `pgcolorbar`. You can install those last two simply with `pip cmlib` and `pip pgcolorbar`

**Comment by titusjan** [comment]
Should be closed with Argos 0.3. Please let me know if the issue persists.
