### ISSUE TITLE
Export dataset

### ISSUE THREAD

**Issue by debbes80** [titusjan/argos#19]
Often I want to quickly export a dataset while browsing a h5 file. I could do this via the table view and select all and copy/paste, but it is a bit cumbersome and for (large) images it is even more difficult.
The way I do it now is open a jupyter notebook and copy the Path from argos and open/save the data with h5py.

It would be great if there was a Export to... option in the right-click menu when clicking a dataset.

**Comment by titusjan** [comment]
Sorry for the late reply. I want to keep Argos a read-only program, so I don't want to export to file. I could consider exporting a data set to the clipboard in another format, if that would somehow help you.

In the mean time I made a new release of Argos, version 0.4.0. It contains a _"copy path to clipboard"_ item in the context menu of the data tree. Perhaps this makes it easier for you to copy the path in your notebook.
