### ISSUE TITLE
Add environment.yml

### ISSUE THREAD

**Issue by rsignell-usgs** [titusjan/argos#6]
Add environment.yml for conda users

**Comment by titusjan** [comment]
I will take a look at it.

**Comment by rsignell-usgs** [comment]
I submitted the PR here: https://github.com/titusjan/argos/pull/7

**Comment by titusjan** [comment]
Closed by commit [ebea2f8](https://github.com/titusjan/argos/commit/ebea2f8554e237ca8c2de84cd2292ce7973c9bd9)
